# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        usuarios:
            entity:
                class: AppBundle\Entity\Usuario
                property: correoElectronico

    encoders:
        AppBundle\Entity\Usuario: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ARBITRO, ROLE_COMENTARISTA]
        ROLE_ARBITRO: [ROLE_USER]
        ROLE_COMENTARISTA: [ROLE_USER]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # Dejamos el acceso anónimo para que los visitantes
            # puedan ver los resultados de los partidos
            anonymous: ~

            form_login:
                login_path: usuario_entrar
                check_path: usuario_comprobar

            logout:
                path: usuario_salir
                target: usuario_entrar